apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "app": "spring-boot-api",
      "version": "{{ .Chart.AppVersion }}"
    }
