apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ randAlphaNum 20 | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
